### ISSUE TITLE
OData v4

### ISSUE THREAD

**Issue by christophwille** [PowerShell/ODataUtils#13]
There seems to be https://github.com/PowerShell/ODataUtils/blob/master/src/ModuleGeneration/Microsoft.PowerShell.ODataV4Adapter.ps1 however the 1.0 to 3.0 version check is hardcoded in https://github.com/PowerShell/ODataUtils/blob/master/src/ModuleGeneration/Microsoft.PowerShell.ODataAdapter.ps1#L89

How is this supposed to work then with v4 using the instructions? (https://docs.microsoft.com/en-us/powershell/wmf/5.0/odata_overview)

Import-Module Microsoft.PowerShell.ODataUtils -Force
$generatedProxyModuleDir = 'd:\home\mymodule.psd1'
$uri = "https://localhost:44300/api/"
Export-ODataEndpointProxy -Uri $uri -OutputModule $generatedProxyModuleDir -Force -AllowUnSecureConnection -Verbose -AllowClobber

Given that the last commit is from Dec 2016, is this library deprecated? If so, how am I supposed to be using OData endpoints in PS?

**Comment by chwilfing** [comment]
As far as I see - you can change the Max Version to 4.0 without issues. tested against your own API (Delegate 365 Demo Tenant). Module import does work, localization data import has some problems due to language settings on local client but that can be worked around with some dirty hacking. 

`
Import-LocalizedData -BindingVariable 'LocalizedData' -FileName Microsoft.PowerShell.ODataUtilsStrings.psd1 -BaseDirectory $PSScriptRoot -UICulture 'en-GB'
`

**Comment by tonipohl** [comment]
So, an "en-us" ... "works on my machine"-issue ;) Thx @christophwille & @chwilfing !
